// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfuv-jkxn-TuMLl0yNXVryWdGva6_aBxA',
    appId: '1:723640289533:web:6479604917b46255a0d694',
    messagingSenderId: '723640289533',
    projectId: 'sipelanin',
    authDomain: 'sipelanin.firebaseapp.com',
    databaseURL: 'https://sipelanin-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sipelanin.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX321qHtBZU4TJwZtRhur3KVCTYRmAvQQ',
    appId: '1:723640289533:android:7b080145eb364963a0d694',
    messagingSenderId: '723640289533',
    projectId: 'sipelanin',
    databaseURL: 'https://sipelanin-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sipelanin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn6g7bAJVxJKMoxHdIxwR1f_P85lv1y2E',
    appId: '1:723640289533:ios:f07e73ba55a457afa0d694',
    messagingSenderId: '723640289533',
    projectId: 'sipelanin',
    databaseURL: 'https://sipelanin-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sipelanin.firebasestorage.app',
    iosBundleId: 'com.example.sipelanin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn6g7bAJVxJKMoxHdIxwR1f_P85lv1y2E',
    appId: '1:723640289533:ios:f07e73ba55a457afa0d694',
    messagingSenderId: '723640289533',
    projectId: 'sipelanin',
    databaseURL: 'https://sipelanin-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sipelanin.firebasestorage.app',
    iosBundleId: 'com.example.sipelanin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfuv-jkxn-TuMLl0yNXVryWdGva6_aBxA',
    appId: '1:723640289533:web:460a299f66f8be91a0d694',
    messagingSenderId: '723640289533',
    projectId: 'sipelanin',
    authDomain: 'sipelanin.firebaseapp.com',
    databaseURL: 'https://sipelanin-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sipelanin.firebasestorage.app',
  );
}
